package com.iispl.dao;

import com.iispl.connectionpool.ConnectionPool;
import com.iispl.entity.DebitTransaction;
import com.iispl.entity.SourceSystem;
import com.iispl.enums.ChannelType;
import com.iispl.enums.ProcessingStatus;
import com.iispl.enums.SourceType;
import com.iispl.enums.TransactionStatus;
import com.iispl.enums.TransactionType;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class DebitTransactionDaoImpl implements DebitTransactionDao {

    private final DataSource dataSource = ConnectionPool.getDataSource();

    // -----------------------------------------------------------------------
    // Persist a new debit transaction record.
    // incoming_tnx_id is auto-generated by the DB; we retrieve it afterwards.
    // -----------------------------------------------------------------------
    @Override
    public DebitTransaction save(DebitTransaction txn) {
        String sql = "INSERT INTO debit_transaction "
                + "(source_system_id, source_system_ref_id, transaction_type, channel_type, "
                + " from_bank_name, to_bank_name, amount, processing_status, "
                + " ingestion_time_stamp, batch_id, debit_account_id) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setLong(1,       txn.getSourceSystem().getSourceSystemId()); // FK to source_system table
            ps.setLong(2,       txn.getIncomingTnxId());                    // FIX: source_system_ref_id = the source's own txn reference ID
            ps.setString(3,     txn.getTransactionType().name());
            ps.setString(4,     txn.getChannelType().name());
            ps.setString(5,     txn.getFromBankName());
            ps.setString(6,     txn.getToBankName());
            ps.setBigDecimal(7, txn.getAmount());
            ps.setString(8,     txn.getProcessingStatus().name());
            ps.setTimestamp(9,  Timestamp.valueOf(txn.getIngestionTimeStamp()));
            ps.setString(10,    txn.getBatchId());
            ps.setLong(11,      txn.getDebitAccountId());

            ps.executeUpdate();

            try (ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) {
                    txn.setIncomingTnxId(rs.getLong(1)); // sets the auto-generated incoming_tnx_id back on the entity
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Error saving debit transaction: " + e.getMessage(), e);
        }
        return txn;
    }

    // -----------------------------------------------------------------------
    // Fetch all debit transactions in the system.
    // -----------------------------------------------------------------------
    @Override
    public List<DebitTransaction> findAllTransactions() {
        String sql = "SELECT dt.*, ss.source_type, ss.file_path "
                   + "FROM debit_transaction dt "
                   + "JOIN source_system ss ON dt.source_system_id = ss.source_system_id";

        List<DebitTransaction> list = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                list.add(mapRow(rs));
            }

        } catch (SQLException e) {
            throw new RuntimeException("Error fetching all debit transactions: " + e.getMessage(), e);
        }
        return list;
    }

    // -----------------------------------------------------------------------
    // Fetch a single debit transaction by its primary key; returns null if not found.
    // -----------------------------------------------------------------------
    @Override
    public DebitTransaction findById(Long id) {
        String sql = "SELECT dt.*, ss.source_type, ss.file_path "
                   + "FROM debit_transaction dt "
                   + "JOIN source_system ss ON dt.source_system_id = ss.source_system_id "
                   + "WHERE dt.incoming_tnx_id = ?";

        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return mapRow(rs);
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Error finding debit transaction by id " + id + ": " + e.getMessage(), e);
        }
        return null;
    }

    // -----------------------------------------------------------------------
    // Assign or update the settlement batch ID on a transaction.
    // -----------------------------------------------------------------------
    @Override
    public void updateBatchId(Long transactionId, String settlementBatchId) {
        String sql = "UPDATE debit_transaction SET batch_id = ? WHERE incoming_tnx_id = ?";

        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, settlementBatchId);
            ps.setLong(2,   transactionId);
            ps.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(
                    "Error updating batch id for transaction " + transactionId + ": " + e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // Fetch all debit transactions belonging to a specific debit account.
    // -----------------------------------------------------------------------
    @Override
    public List<DebitTransaction> findByDebitAccountId(Long debitAccountId) {
        String sql = "SELECT dt.*, ss.source_type, ss.file_path "
                   + "FROM debit_transaction dt "
                   + "JOIN source_system ss ON dt.source_system_id = ss.source_system_id "
                   + "WHERE dt.debit_account_id = ?";

        List<DebitTransaction> list = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, debitAccountId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(mapRow(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException(
                    "Error finding transactions for debit account " + debitAccountId + ": " + e.getMessage(), e);
        }
        return list;
    }

    // -----------------------------------------------------------------------
    // Fetch all debit transactions with a given settlement batch ID.
    // -----------------------------------------------------------------------
    @Override
    public List<DebitTransaction> findBySettlementBatchId(String settlementBatchId) {
        String sql = "SELECT dt.*, ss.source_type, ss.file_path "
                   + "FROM debit_transaction dt "
                   + "JOIN source_system ss ON dt.source_system_id = ss.source_system_id "
                   + "WHERE dt.batch_id = ?";

        List<DebitTransaction> list = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, settlementBatchId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(mapRow(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException(
                    "Error finding transactions for batch " + settlementBatchId + ": " + e.getMessage(), e);
        }
        return list;
    }

    // -----------------------------------------------------------------------
    // Fetch all debit transactions with a specific TransactionStatus.
    // TransactionStatus drives the filter on the processing_status column.
    // -----------------------------------------------------------------------
    @Override
    public List<DebitTransaction> findByStatus(TransactionStatus status) {
        String sql = "SELECT dt.*, ss.source_type, ss.file_path "
                   + "FROM debit_transaction dt "
                   + "JOIN source_system ss ON dt.source_system_id = ss.source_system_id "
                   + "WHERE dt.processing_status = ?";

        List<DebitTransaction> list = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, status.name());
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(mapRow(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException(
                    "Error finding transactions by status " + status + ": " + e.getMessage(), e);
        }
        return list;
    }

    // -----------------------------------------------------------------------
    // Fetch all debit transactions falling within a date range (inclusive).
    // -----------------------------------------------------------------------
    @Override
    public List<DebitTransaction> findByDateRange(LocalDateTime from, LocalDateTime to) {
        String sql = "SELECT dt.*, ss.source_type, ss.file_path "
                   + "FROM debit_transaction dt "
                   + "JOIN source_system ss ON dt.source_system_id = ss.source_system_id "
                   + "WHERE dt.ingestion_time_stamp BETWEEN ? AND ?";

        List<DebitTransaction> list = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setTimestamp(1, Timestamp.valueOf(from));
            ps.setTimestamp(2, Timestamp.valueOf(to));
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(mapRow(rs));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Error finding transactions in date range: " + e.getMessage(), e);
        }
        return list;
    }

    // -----------------------------------------------------------------------
    // Update the processing status of a specific transaction.
    // -----------------------------------------------------------------------
    @Override
    public void updateStatus(Long transactionId, TransactionStatus newStatus) {
        String sql = "UPDATE debit_transaction SET processing_status = ? WHERE incoming_tnx_id = ?";

        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, newStatus.name());
            ps.setLong(2,   transactionId);
            ps.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(
                    "Error updating status for transaction " + transactionId + ": " + e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // Maps a ResultSet row (JOIN of debit_transaction + source_system) to a
    // fully-populated DebitTransaction object.
    // -----------------------------------------------------------------------
    private DebitTransaction mapRow(ResultSet rs) throws SQLException {
        SourceSystem sourceSystem = new SourceSystem(
                rs.getLong("source_system_id"),
                SourceType.valueOf(rs.getString("source_type")),
                rs.getString("file_path")
        );
        return new DebitTransaction(
                rs.getLong("incoming_tnx_id"),
                sourceSystem,
                rs.getLong("source_system_id"),
                TransactionType.valueOf(rs.getString("transaction_type")),
                ChannelType.valueOf(rs.getString("channel_type")),
                rs.getString("from_bank_name"),
                rs.getString("to_bank_name"),
                rs.getBigDecimal("amount"),
                ProcessingStatus.valueOf(rs.getString("processing_status")),
                rs.getTimestamp("ingestion_time_stamp").toLocalDateTime(),
                rs.getString("batch_id"),
                rs.getLong("debit_account_id")
        );
    }
}